export const genresData = [
  { id: 1, name: "Shooter" },
  { id: 2, name: "Acción" },
  { id: 3, name: "Multiplayer" },
  { id: 4, name: "MMOARPG" },
  { id: 5, name: "Aventura" },
  { id: 6, name: "ARPG" },
  { id: 7, name: "Estrategia" },
  { id: 8, name: "Simulación" },
  { id: 9, name: "MMORPG" },
  { id: 10, name: "Lucha" },
  { id: 11, name: "RPG de Acción" },
  { id: 12, name: "Fantasía" },
  { id: 13, name: "Battle Royale" },
];

export const companyData = [
  { id: 28, name: "Desconocido" },
  { id: 1, name: "Activision Blizzard" },
  { id: 2, name: "Amazon Games" },
  { id: 3, name: "Warner Bros" },
  { id: 4, name: "Blizzard Entertainment" },
  { id: 5, name: "KRAFTON, Inc." },
  { id: 6, name: "InnoGames" },
  { id: 7, name: "Bigpoint" },
  { id: 8, name: "Player First Games" },
  { id: 9, name: "miHoYo" },
  { id: 10, name: "Mediatonic" },
  { id: 11, name: "YOOZOO Games" },
  { id: 12, name: "Cryptic Studios" },
  { id: 13, name: "R2 Games" },
  { id: 14, name: "Gala Lab" },
  { id: 15, name: "Sega" },
  { id: 16, name: "Gaijin" },
  { id: 17, name: "Wargaming" },
  { id: 18, name: "NetherRealm Studios" },
  { id: 19, name: "The Vanishing" },
  { id: 20, name: "Smilegate RPG" },
  { id: 21, name: "Darkflow Software" },
  { id: 22, name: "343 Industries" },
  { id: 23, name: "GTArcade" },
  { id: 24, name: "Perfect World Entertainment" },
  { id: 25, name: "Xbox Game Studios" },
  { id: 26, name: "Targem" },
  { id: 27, name: "The Astronauts" },
];
export const regexPatterns = {
  title: /^^[a-zA-Z0-9\s]{1,255}$/,
  price: /^\d{1,6}$/,
  offer: /^(?:100|\d{1,2})$/,
  stock: /^(?:[1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$/,
  genres: /^\d+$/,
  release_date: /^\d{4}-\d{2}-\d{2}$/,
  developer: /^\d+$/,
  publisher: /^\d+$/,
  short_description: /^.{1,255}$/,
};

export const initialFormData = {
  img: "",
  title: "",
  price: "",
  offer: "",
  stock: "",
  genre1: "",
  genre2: "",
  genre3: "",
  release_date: "",
  developer: "",
  publisher: "",
  short_description: "",
};

export const initialFormErrors = {
  img: false,
  title: false,
  price: false,
  offer: false,
  stock: false,
  genres: false,
  release_date: false,
  developer: false,
  publisher: false,
  short_description: false,
};
